# ════════════════════════════════════════════════════════════
# 📖 lectures/ml_intro_lec1.py
# Machine Learning - Lecture 1: Introduction
# Dr. Sara Sweidan
# 35 MCQ + 15 True/False = 50 Questions
# ════════════════════════════════════════════════════════════

QUESTIONS = [

    # ══════════════════════════════════════════════
    # ✅ MCQ Questions (1–35)
    # ══════════════════════════════════════════════

    {
        "q": "What is Machine Learning?",
        "type": "mcq",
        "options": [
            "A branch of AI that allows computers to learn from past data automatically",
            "A programming language used to build websites",
            "A method to manually write rules for computers",
            "A type of database management system",
        ],
        "ans": "A branch of AI that allows computers to learn from past data automatically",
        "explain_correct": "✅ Correct! Machine Learning is a branch of AI concerned with developing algorithms that allow a computer to learn automatically from past data and experiences.",
        "explain_wrong": "❌ Machine Learning is not about manually writing rules — it's about letting computers discover those rules automatically from data.",
    },
    {
        "q": "What is 'training data' in Machine Learning?",
        "type": "mcq",
        "options": [
            "Data used to test the final model",
            "Historical data used to train the model",
            "Data generated randomly by the algorithm",
            "Data used only for visualization",
        ],
        "ans": "Historical data used to train the model",
        "explain_correct": "✅ Correct! Historical data is called training data — the model learns patterns from it.",
        "explain_wrong": "❌ Training data is not test data. Test data is used after training to evaluate the model.",
    },
    {
        "q": "According to Professor Mitchell's formal definition, what does 'E' represent in Machine Learning?",
        "type": "mcq",
        "options": [
            "Evaluation metric",
            "Experience (the dataset the algorithm learns from)",
            "Efficiency of the algorithm",
            "Error rate",
        ],
        "ans": "Experience (the dataset the algorithm learns from)",
        "explain_correct": "✅ Correct! E = Experience. It represents the data the learning algorithm consumes and learns inherent patterns from.",
        "explain_wrong": "❌ In Mitchell's definition: T = Task, P = Performance measure, E = Experience (the training data).",
    },
    {
        "q": "According to Professor Mitchell's formal definition, what does 'T' represent?",
        "type": "mcq",
        "options": [
            "Training data",
            "The task the program is learning to perform",
            "The total number of features",
            "The type of model used",
        ],
        "ans": "The task the program is learning to perform",
        "explain_correct": "✅ Correct! T = Task. Examples include classification, regression, anomaly detection, translation, etc.",
        "explain_wrong": "❌ T is not Training data — T stands for the Task being learned.",
    },
    {
        "q": "Which of the following is a valid performance measure (P) in Machine Learning?",
        "type": "mcq",
        "options": [
            "Number of training samples",
            "Accuracy, Precision, Recall, F1 Score",
            "Number of features in the dataset",
            "The programming language used",
        ],
        "ans": "Accuracy, Precision, Recall, F1 Score",
        "explain_correct": "✅ Correct! Performance measures include accuracy, precision, recall, F1 score, error rate, and others used to evaluate how well the model performs.",
        "explain_wrong": "❌ Number of samples or features are dataset properties, not performance measures.",
    },
    {
        "q": "In traditional programming, what are the inputs?",
        "type": "mcq",
        "options": [
            "Data + Output → Program",
            "Data + Program → Output",
            "Program + Output → Data",
            "Output only → Program",
        ],
        "ans": "Data + Program → Output",
        "explain_correct": "✅ Correct! Traditional programming takes Data and a Program as input and produces Output.",
        "explain_wrong": "❌ In Machine Learning it's reversed: Data + Output (labels) → Program (model).",
    },
    {
        "q": "In Machine Learning, what are the inputs and what is the output?",
        "type": "mcq",
        "options": [
            "Data + Program → Output",
            "Data only → Output",
            "Data + Output (labels) → Program (model)",
            "Program + Output → Data",
        ],
        "ans": "Data + Output (labels) → Program (model)",
        "explain_correct": "✅ Correct! ML flips traditional programming: you provide Data and known Outputs, and ML produces the Program (model).",
        "explain_wrong": "❌ That's traditional programming. ML reverses the flow to learn the program from data.",
    },
    {
        "q": "Which of the following is NOT a feature of Machine Learning?",
        "type": "mcq",
        "options": [
            "It can learn from past data",
            "It can improve automatically",
            "It requires manually written rules for every scenario",
            "It can deal with huge amounts of data",
        ],
        "ans": "It requires manually written rules for every scenario",
        "explain_correct": "✅ Correct! ML does NOT require manually written rules — that's what makes it different from traditional programming.",
        "explain_wrong": "❌ Writing rules manually is the opposite of Machine Learning — ML discovers rules automatically from data.",
    },
    {
        "q": "Which of the following is a reason we make machines learn?",
        "type": "mcq",
        "options": [
            "When humans have complete expertise and can easily formalize it",
            "When scenarios never change over time",
            "When human expertise in a domain is lacking or hard to formalize",
            "When the dataset is very small",
        ],
        "ans": "When human expertise in a domain is lacking or hard to formalize",
        "explain_correct": "✅ Correct! We use ML when there's lack of human expertise, when behavior changes over time, or when it's hard to translate expertise into code (e.g., speech recognition).",
        "explain_wrong": "❌ If humans can easily formalize their expertise, traditional programming may be sufficient.",
    },
    {
        "q": "What happens to prediction accuracy as the amount of training data increases?",
        "type": "mcq",
        "options": [
            "Accuracy decreases",
            "Accuracy stays the same",
            "Accuracy improves",
            "The model stops working",
        ],
        "ans": "Accuracy improves",
        "explain_correct": "✅ Correct! More data → better predictions. The model learns more patterns from larger datasets.",
        "explain_wrong": "❌ More data generally helps, not hurts. More data reduces variance and improves generalization.",
    },
    {
        "q": "What are the four steps of how machines learn?",
        "type": "mcq",
        "options": [
            "Collection, Storage, Analysis, Reporting",
            "Data Storage, Abstraction, Generalization, Evaluation",
            "Training, Testing, Validation, Deployment",
            "Input, Processing, Output, Feedback",
        ],
        "ans": "Data Storage, Abstraction, Generalization, Evaluation",
        "explain_correct": "✅ Correct! The four steps are: Data Storage → Abstraction → Generalization → Evaluation.",
        "explain_wrong": "❌ The correct steps are Data Storage, Abstraction, Generalization, and Evaluation — not the other options.",
    },
    {
        "q": "What is 'Abstraction' in the machine learning process?",
        "type": "mcq",
        "options": [
            "Collecting raw data from databases",
            "Translating stored data into broader representations and concepts (building a model)",
            "Measuring model performance on test data",
            "Deploying the model in production",
        ],
        "ans": "Translating stored data into broader representations and concepts (building a model)",
        "explain_correct": "✅ Correct! Abstraction involves translating raw data into a model — a broader representation that summarizes the data's patterns.",
        "explain_wrong": "❌ Abstraction is not about collecting data or evaluation. It's the step where meaning is assigned to data via a model.",
    },
    {
        "q": "What is the process of fitting a model to a dataset called?",
        "type": "mcq",
        "options": [
            "Testing",
            "Deployment",
            "Training",
            "Evaluation",
        ],
        "ans": "Training",
        "explain_correct": "✅ Correct! Fitting a model to a dataset is called Training. The human teacher trains the machine student to understand data in a specific way.",
        "explain_wrong": "❌ Testing is done after training. Deployment is putting the model in production. Evaluation measures performance.",
    },
    {
        "q": "What does 'Generalization' mean in Machine Learning?",
        "type": "mcq",
        "options": [
            "Memorizing all training examples perfectly",
            "Applying learned knowledge to new, unseen tasks similar to training",
            "Collecting more training data",
            "Reducing model complexity",
        ],
        "ans": "Applying learned knowledge to new, unseen tasks similar to training",
        "explain_correct": "✅ Correct! Generalization is turning abstracted knowledge into a form that can be applied to future tasks that are similar but not identical to training tasks.",
        "explain_wrong": "❌ Memorizing training data is overfitting, not generalization. Generalization means the model works on new data too.",
    },
    {
        "q": "What is 'Bias' in a Machine Learning model?",
        "type": "mcq",
        "options": [
            "When the model performs perfectly on all data",
            "When the conclusions are systematically erroneous or wrong in a predictable manner",
            "When the model has too many parameters",
            "When the training data is too large",
        ],
        "ans": "When the conclusions are systematically erroneous or wrong in a predictable manner",
        "explain_correct": "✅ Correct! Bias means the algorithm makes systematic errors — it's wrong in a predictable, consistent way. High bias → underfitting.",
        "explain_wrong": "❌ Bias is not about having too many parameters (that's variance/overfitting). Bias is about systematic error.",
    },
    {
        "q": "What is 'Overfitting' in Machine Learning?",
        "type": "mcq",
        "options": [
            "When the model performs poorly on training data",
            "When the model tries to model noise in training data, performing well on training but poorly on test data",
            "When the model is too simple to capture patterns",
            "When we don't have enough training data",
        ],
        "ans": "When the model tries to model noise in training data, performing well on training but poorly on test data",
        "explain_correct": "✅ Correct! Overfitting: high training accuracy but low test accuracy. The model memorized noise instead of learning general patterns. Low Bias, High Variance.",
        "explain_wrong": "❌ Performing poorly on training data is underfitting (high bias). Overfitting is when training accuracy is great but test accuracy is poor.",
    },
    {
        "q": "An underfitting model has:",
        "type": "mcq",
        "options": [
            "Low bias and low variance",
            "High bias and high variance",
            "High bias and low variance",
            "Low bias and high variance",
        ],
        "ans": "High bias and low variance",
        "explain_correct": "✅ Correct! Underfitting = High Bias + Low Variance. The model is too simple — it can't capture the underlying patterns.",
        "explain_wrong": "❌ Overfitting is Low Bias + High Variance. Underfitting is High Bias + Low Variance.",
    },
    {
        "q": "An overfitting model has:",
        "type": "mcq",
        "options": [
            "High bias and low variance",
            "Low bias and high variance",
            "High bias and high variance",
            "Low bias and low variance",
        ],
        "ans": "Low bias and high variance",
        "explain_correct": "✅ Correct! Overfitting = Low Bias + High Variance. The model fits training data too well but fails on new data.",
        "explain_wrong": "❌ High bias + low variance = underfitting. Low bias + high variance = overfitting.",
    },
    {
        "q": "What is 'Variance' in Machine Learning?",
        "type": "mcq",
        "options": [
            "Measures the accuracy of the model on training data",
            "Measures the precision or specificity — how much the model changes as training data varies",
            "The number of features in the dataset",
            "The difference between training and test set sizes",
        ],
        "ans": "Measures the precision or specificity — how much the model changes as training data varies",
        "explain_correct": "✅ Correct! Variance measures precision — low variance means the model is stable and doesn't change much when the training set changes.",
        "explain_wrong": "❌ Bias measures accuracy. Variance measures how sensitive the model is to changes in training data.",
    },
    {
        "q": "Which fix helps address HIGH VARIANCE (overfitting)?",
        "type": "mcq",
        "options": [
            "Add more features",
            "Use a more complex model",
            "Get more training examples or reduce features",
            "Train for fewer iterations",
        ],
        "ans": "Get more training examples or reduce features",
        "explain_correct": "✅ Correct! To fix high variance: get more training data, use a smaller feature set, or apply regularization.",
        "explain_wrong": "❌ Adding more features or complexity makes overfitting worse. To fix overfitting, simplify the model or add more data.",
    },
    {
        "q": "Which fix helps address HIGH BIAS (underfitting)?",
        "type": "mcq",
        "options": [
            "Reduce training data",
            "Use a simpler model",
            "Add more features or use a more complex model",
            "Apply regularization",
        ],
        "ans": "Add more features or use a more complex model",
        "explain_correct": "✅ Correct! To fix high bias: add more features, increase model complexity, or train longer.",
        "explain_wrong": "❌ Regularization and simpler models help overfitting. High bias (underfitting) needs MORE complexity.",
    },
    {
        "q": "Supervised Learning is best described as:",
        "type": "mcq",
        "options": [
            "Learning from unlabeled data to find hidden patterns",
            "Learning from labeled data where the desired output is known",
            "Learning by trial and error with rewards and penalties",
            "Learning from a mix of labeled and unlabeled data",
        ],
        "ans": "Learning from labeled data where the desired output is known",
        "explain_correct": "✅ Correct! In supervised learning, the algorithm learns from labeled training data — each example has an input and a known correct output.",
        "explain_wrong": "❌ Unlabeled data is unsupervised. Trial and error with rewards is reinforcement learning.",
    },
    {
        "q": "In supervised learning Classification, the output is:",
        "type": "mcq",
        "options": [
            "A continuous numerical value",
            "A discrete categorical label",
            "A probability distribution",
            "A cluster of similar items",
        ],
        "ans": "A discrete categorical label",
        "explain_correct": "✅ Correct! Classification produces discrete outputs like spam/not spam, malignant/benign, or Good/Bad.",
        "explain_wrong": "❌ Continuous outputs belong to Regression. Classification outputs are discrete categories.",
    },
    {
        "q": "Predicting house prices based on location and year is an example of:",
        "type": "mcq",
        "options": [
            "Classification",
            "Clustering",
            "Regression",
            "Reinforcement Learning",
        ],
        "ans": "Regression",
        "explain_correct": "✅ Correct! Predicting a continuous value like price is Regression. Output y ∈ R (real numbers).",
        "explain_wrong": "❌ Classification outputs discrete classes. Regression outputs continuous values like prices, temperatures, etc.",
    },
    {
        "q": "Unsupervised Learning works with:",
        "type": "mcq",
        "options": [
            "Labeled data with known outputs",
            "Only input data with no labels",
            "Data with rewards and penalties",
            "Data with at least 50% labels",
        ],
        "ans": "Only input data with no labels",
        "explain_correct": "✅ Correct! Unsupervised learning uses only input vectors {x1, x2, ..., xn} with no labels. The algorithm discovers structure on its own.",
        "explain_wrong": "❌ Labeled data is for supervised learning. Unsupervised learning finds patterns without any predefined labels.",
    },
    {
        "q": "Which of the following is an example of Unsupervised Learning?",
        "type": "mcq",
        "options": [
            "Email spam classification",
            "Predicting if a tumor is malignant",
            "Grouping customers into market segments",
            "Predicting stock prices",
        ],
        "ans": "Grouping customers into market segments",
        "explain_correct": "✅ Correct! Grouping/clustering is unsupervised — no predefined labels exist, the algorithm discovers natural groupings.",
        "explain_wrong": "❌ Classification (spam, tumor) is supervised. Clustering (customer segments) is unsupervised.",
    },
    {
        "q": "K-means is an example of which type of clustering?",
        "type": "mcq",
        "options": [
            "Hierarchical clustering",
            "Density-based clustering",
            "Centroid-based clustering",
            "Distribution-based clustering",
        ],
        "ans": "Centroid-based clustering",
        "explain_correct": "✅ Correct! K-means is a centroid-based clustering method. DBSCAN and OPTICS are density-based. Gaussian mixture models are distribution-based.",
        "explain_wrong": "❌ K-means uses centroids (centers) to define clusters. DBSCAN uses density. Hierarchical builds a tree structure.",
    },
    {
        "q": "Principal Component Analysis (PCA) is used for:",
        "type": "mcq",
        "options": [
            "Classification of labeled data",
            "Dimensionality Reduction",
            "Reinforcement learning",
            "Anomaly detection only",
        ],
        "ans": "Dimensionality Reduction",
        "explain_correct": "✅ Correct! PCA is a popular dimensionality reduction technique. It reduces the number of features while preserving the most important information.",
        "explain_wrong": "❌ PCA reduces dimensions, it's not a classifier. It's an unsupervised feature extraction method.",
    },
    {
        "q": "In Reinforcement Learning, the agent learns by:",
        "type": "mcq",
        "options": [
            "Studying labeled examples provided by a teacher",
            "Finding hidden patterns in unlabeled data",
            "Receiving rewards or penalties based on actions taken in an environment",
            "Copying human behavior directly",
        ],
        "ans": "Receiving rewards or penalties based on actions taken in an environment",
        "explain_correct": "✅ Correct! RL cycle: Get Environment State → Perform Action → Get Reward/Penalty → Update Action Policies (Learning).",
        "explain_wrong": "❌ Labeled examples = supervised. Hidden patterns = unsupervised. RL learns through trial-and-error with rewards.",
    },
    {
        "q": "Association Rule Mining is used for:",
        "type": "mcq",
        "options": [
            "Predicting exact future prices",
            "Detecting and predicting transactional patterns (e.g., market basket analysis)",
            "Reducing the number of features",
            "Classifying images",
        ],
        "ans": "Detecting and predicting transactional patterns (e.g., market basket analysis)",
        "explain_correct": "✅ Correct! Association rules detect patterns in transactions — e.g., customers who buy milk also tend to buy bread.",
        "explain_wrong": "❌ Association rules are about finding frequent item co-occurrences, not price prediction or image classification.",
    },
    {
        "q": "The standard ML pipeline steps are:",
        "type": "mcq",
        "options": [
            "Collect → Code → Deploy",
            "Data Retrieval → Data Preparation → Modeling → Evaluation & Tuning → Deployment",
            "Train → Test → Repeat",
            "Feature Engineering → Model Building → Done",
        ],
        "ans": "Data Retrieval → Data Preparation → Modeling → Evaluation & Tuning → Deployment",
        "explain_correct": "✅ Correct! The 5 steps are: 1-Data Retrieval, 2-Data Preparation, 3-Modeling, 4-Evaluation & Tuning, 5-Deployment & Monitoring.",
        "explain_wrong": "❌ The full pipeline has 5 steps including data retrieval, preparation, modeling, evaluation, and finally deployment.",
    },
    {
        "q": "A feature that takes categories with a natural order (e.g., Small, Medium, Large) is called:",
        "type": "mcq",
        "options": [
            "Numeric",
            "Nominal",
            "Ordinal",
            "Binary",
        ],
        "ans": "Ordinal",
        "explain_correct": "✅ Correct! Ordinal = categorical variable with ordered categories. Examples: sizes (S/M/L), satisfaction (low/medium/high).",
        "explain_wrong": "❌ Nominal has categories with no order (e.g., colors). Numeric is numbers. Ordinal has order.",
    },
    {
        "q": "Which algorithm is used for Instance-Based Learning?",
        "type": "mcq",
        "options": [
            "Linear Regression",
            "K-Nearest Neighbor (KNN)",
            "Decision Tree",
            "Neural Network",
        ],
        "ans": "K-Nearest Neighbor (KNN)",
        "explain_correct": "✅ Correct! KNN is the classic instance-based learning algorithm — it classifies new data by looking at the similarity to stored training examples.",
        "explain_wrong": "❌ Decision Trees and Linear Regression are model-based. KNN is instance-based (memorizes training data directly).",
    },
    {
        "q": "Noisy data in ML refers to:",
        "type": "mcq",
        "options": [
            "Data that is very large in volume",
            "Data caused by random events like measurement errors, missing values, or corrupted values",
            "Data stored in audio format",
            "Data collected from social media",
        ],
        "ans": "Data caused by random events like measurement errors, missing values, or corrupted values",
        "explain_correct": "✅ Correct! Noisy data comes from imprecise sensors, human errors in surveys, missing values, or corrupted data. Modeling noise leads to overfitting.",
        "explain_wrong": "❌ Noisy data is about data quality issues, not volume or format.",
    },
    {
        "q": "Machine Learning is considered a Multi-Disciplinary field. Which fields does it combine?",
        "type": "mcq",
        "options": [
            "Art, Music, and Literature",
            "Statistics, Mathematics, Computer Science, and Data Mining",
            "Biology, Chemistry, and Physics only",
            "Geography, History, and Economics",
        ],
        "ans": "Statistics, Mathematics, Computer Science, and Data Mining",
        "explain_correct": "✅ Correct! ML sits at the intersection of Statistics, Mathematics, Computer Science, Data Mining, and AI — it's truly multidisciplinary.",
        "explain_wrong": "❌ ML is a technical field combining Statistics, Math, CS, and Data Science — not humanities or physical sciences.",
    },
    {
        "q": "In ML, 'Data Preparation' includes:",
        "type": "mcq",
        "options": [
            "Only collecting raw data",
            "Data integration, wrangling, cleaning, normalization, and feature selection",
            "Only deploying the model",
            "Writing the algorithm code only",
        ],
        "ans": "Data integration, wrangling, cleaning, normalization, and feature selection",
        "explain_correct": "✅ Correct! Data Preparation includes: Integration, Wrangling (cleaning/normalization), and Attribute generation/selection.",
        "explain_wrong": "❌ Data preparation is much more than just collection — it includes cleaning, normalizing, and selecting relevant features.",
    },


    # ══════════════════════════════════════════════
    # ✅ True / False Questions (36–50)
    # ══════════════════════════════════════════════

    {
        "q": "Machine Learning is a subset of Artificial Intelligence (AI).",
        "type": "tf",
        "options": ["True", "False"],
        "ans": "True",
        "explain_correct": "✅ Correct! ML is a subset of AI. AI is the broader field, and ML focuses on self-learning and adaptive systems within it.",
        "explain_wrong": "❌ ML is indeed a subset of AI — shown clearly in the Venn diagram from the lecture.",
    },
    {
        "q": "In Machine Learning, more data always leads to worse predictions.",
        "type": "tf",
        "options": ["True", "False"],
        "ans": "False",
        "explain_correct": "✅ Correct! More data generally leads to BETTER predictions, not worse. More data = better generalization.",
        "explain_wrong": "❌ Actually the opposite is true: More data → better predictions (improved model accuracy).",
    },
    {
        "q": "The process of fitting a model to a dataset is called 'Training'.",
        "type": "tf",
        "options": ["True", "False"],
        "ans": "True",
        "explain_correct": "✅ Correct! Fitting a model to training data is called Training — the model learns patterns from the data.",
        "explain_wrong": "❌ Fitting a model to data is indeed called Training.",
    },
    {
        "q": "A model with Training accuracy = 99% and Test accuracy = 60% is an underfitting model.",
        "type": "tf",
        "options": ["True", "False"],
        "ans": "False",
        "explain_correct": "✅ Correct! This is an OVERFITTING model (Low Bias, High Variance). It performs great on training but fails on test data.",
        "explain_wrong": "❌ High train accuracy + low test accuracy = Overfitting, NOT underfitting. Underfitting has poor performance on both.",
    },
    {
        "q": "Supervised learning requires labeled training data.",
        "type": "tf",
        "options": ["True", "False"],
        "ans": "True",
        "explain_correct": "✅ Correct! Supervised learning needs labeled data — each training example has an input and a known output label.",
        "explain_wrong": "❌ Supervised learning DOES require labels. Unsupervised learning works without labels.",
    },
    {
        "q": "Unsupervised learning requires labeled training data.",
        "type": "tf",
        "options": ["True", "False"],
        "ans": "False",
        "explain_correct": "✅ Correct! Unsupervised learning works with UNLABELED data — {x1, x2, ..., xn} with no predefined output labels.",
        "explain_wrong": "❌ Unsupervised learning does NOT use labels. It discovers hidden structure on its own.",
    },
    {
        "q": "Regression is a supervised learning task where the output is a continuous value.",
        "type": "tf",
        "options": ["True", "False"],
        "ans": "True",
        "explain_correct": "✅ Correct! Regression predicts continuous outputs like prices or temperatures. Output y ∈ R (real numbers).",
        "explain_wrong": "❌ Regression does produce continuous outputs. Discrete outputs belong to classification.",
    },
    {
        "q": "Reinforcement Learning learns by receiving labeled examples from a human teacher.",
        "type": "tf",
        "options": ["True", "False"],
        "ans": "False",
        "explain_correct": "✅ Correct! RL does NOT use labeled examples. It learns through trial-and-error: performing actions and receiving rewards or penalties from the environment.",
        "explain_wrong": "❌ Labeled examples = Supervised Learning. RL learns from rewards/penalties, not human-labeled data.",
    },
    {
        "q": "Deep Learning is a subset of Machine Learning.",
        "type": "tf",
        "options": ["True", "False"],
        "ans": "True",
        "explain_correct": "✅ Correct! Deep Learning is a specialized subset of Machine Learning, which is itself a subset of AI.",
        "explain_wrong": "❌ The hierarchy is: AI ⊃ ML ⊃ Deep Learning — each is a subset of the larger field.",
    },
    {
        "q": "Bias measures the precision of a Machine Learning model.",
        "type": "tf",
        "options": ["True", "False"],
        "ans": "False",
        "explain_correct": "✅ Correct! Bias measures ACCURACY (quality) of the model, not precision. Variance measures precision/specificity.",
        "explain_wrong": "❌ Bias = accuracy/quality. Variance = precision/specificity. They measure different things.",
    },
    {
        "q": "K-means is a density-based clustering algorithm.",
        "type": "tf",
        "options": ["True", "False"],
        "ans": "False",
        "explain_correct": "✅ Correct! K-means is a CENTROID-based algorithm. DBSCAN and OPTICS are density-based algorithms.",
        "explain_wrong": "❌ K-means is centroid-based. Density-based methods include DBSCAN and OPTICS.",
    },
    {
        "q": "In the ML pipeline, model deployment comes before model evaluation.",
        "type": "tf",
        "options": ["True", "False"],
        "ans": "False",
        "explain_correct": "✅ Correct! The correct order is: Modeling → Evaluation & Tuning → Deployment. You must evaluate before deploying!",
        "explain_wrong": "❌ You must EVALUATE and TUNE the model before deploying it to production.",
    },
    {
        "q": "Association Rule Mining is an unsupervised learning technique.",
        "type": "tf",
        "options": ["True", "False"],
        "ans": "True",
        "explain_correct": "✅ Correct! Association Rule Mining is an unsupervised technique — it finds patterns in unlabeled transaction data without predefined outputs.",
        "explain_wrong": "❌ Association Rule Mining is indeed unsupervised — no labels are needed to discover item co-occurrences.",
    },
    {
        "q": "An ordinal variable has categories with no natural order (e.g., colors).",
        "type": "tf",
        "options": ["True", "False"],
        "ans": "False",
        "explain_correct": "✅ Correct! Ordinal variables DO have a natural order (e.g., S/M/L, low/medium/high). Variables with no order are called Nominal.",
        "explain_wrong": "❌ Categories WITH order = Ordinal. Categories WITHOUT order (like colors) = Nominal.",
    },
    {
        "q": "Machine Learning models must be evaluated on test data that the model has never seen during training.",
        "type": "tf",
        "options": ["True", "False"],
        "ans": "True",
        "explain_correct": "✅ Correct! Evaluation on unseen test data ensures the model generalizes well — not just memorizing training data.",
        "explain_wrong": "❌ Evaluating only on training data doesn't tell us if the model generalizes. Test data must be new, unseen data.",
    },
]
